version: 2
registries:
  tiptap-pro:
    type: 'npm-registry'
    url: 'https://registry.tiptap.dev'
    token: '${{secrets.TIPTAP_PRO_TOKEN}}'
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    registries:
      - tiptap-pro
