services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - TIPTAP_PRO_TOKEN=${TIPTAP_PRO_TOKEN}
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
    platform: linux/amd64
    container_name: app
    tty: true
    ports:
      - 4000:4000
    command: sh -c "yarn start"
