services:
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx/dev:/etc/nginx/conf.d
      - /etc/ssl:/etc/nginx/ssl

  app:
    build:
      args:
        - PUBLIC_AMPLITUDE_API_KEY=${PUBLIC_AMPLITUDE_API_KEY}
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
