version: '3.7'
services:
  postgres:
    build: ./docker
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - APP_USER=app
      - APP_PASSWORD=password
      - APP_DB=collections
    ports:
      - '6002:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
