name: Report a bug
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to create an issue! Before you begin, please make sure the following is correct:

        - I'm using the [latest version of Collections](https://github.com/collectionscms/collections/releases)
        - There's [no other issue](https://github.com/collectionscms/collections/issues?q=is%3Aissue) that already describes the problem.
  - type: textarea
    attributes:
      label: Describe bugs
      description: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the operation.
    validations:
      required: true
  - type: input
    attributes:
      label: Collections Version
      placeholder: v1.x.x
    validations:
      required: true
