/* eslint-disable max-len */
export const randomString = (length: number): string => {
  const randomChars =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789あいうえおアイウエオｱｲｳｴｵ０１２３４５６７８９';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += randomChars.charAt(Math.floor(Math.random() * randomChars.length));
  }
  return result;
};

export const wordPressXml = `<?xml version="1.0" encoding="UTF-8" ?>
  <!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
  <!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
  <!-- You may use this file to transfer that content from one site to another. -->
  <!-- This file is not intended to serve as a complete backup of your site. -->

  <!-- To import this information into a WordPress site follow these steps: -->
  <!-- 1. Log in to that site as an administrator. -->
  <!-- 2. Go to Tools: Import in the WordPress admin panel. -->
  <!-- 3. Install the "WordPress" importer from the list. -->
  <!-- 4. Activate & Run Importer. -->
  <!-- 5. Upload this file using the form provided on that page. -->
  <!-- 6. You will first be asked to map the authors in this export file to users -->
  <!--    on the site. For each author, you may choose to map to an -->
  <!--    existing user on the site or to create a new user. -->
  <!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
  <!--    contained in this file into your site. -->

    <!-- generator="WordPress/6.3.1" created="2023-09-07 13:04" -->
  <rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/"
  >

  <channel>
    <title>User&#039;s blog</title>
    <link>http://1.234.5.678</link>
    <description></description>
    <pubDate>Thu, 07 Sep 2023 13:04:56 +0000</pubDate>
    <language>en-US</language>
    <wp:wxr_version>1.2</wp:wxr_version>
    <wp:base_site_url>http://1.234.5.678</wp:base_site_url>
    <wp:base_blog_url>http://1.234.5.678</wp:base_blog_url>

      <wp:author><wp:author_id>1</wp:author_id><wp:author_login><![CDATA[user]]></wp:author_login><wp:author_email><![CDATA[user@example.com]]></wp:author_email><wp:author_display_name><![CDATA[user]]></wp:author_display_name><wp:author_first_name><![CDATA[UserName]]></wp:author_first_name><wp:author_last_name><![CDATA[LastName]]></wp:author_last_name></wp:author>

      <wp:category>
      <wp:term_id>4</wp:term_id>
      <wp:category_nicename><![CDATA[blog]]></wp:category_nicename>
      <wp:category_parent><![CDATA[]]></wp:category_parent>
      <wp:cat_name><![CDATA[blog]]></wp:cat_name>
    </wp:category>
      <wp:category>
      <wp:term_id>1</wp:term_id>
      <wp:category_nicename><![CDATA[uncategorized]]></wp:category_nicename>
      <wp:category_parent><![CDATA[]]></wp:category_parent>
      <wp:cat_name><![CDATA[Uncategorized]]></wp:cat_name>
    </wp:category>
        <wp:tag>
      <wp:term_id>13</wp:term_id>
      <wp:tag_slug><![CDATA[post]]></wp:tag_slug>
      <wp:tag_name><![CDATA[post]]></wp:tag_name>
    </wp:tag>
        <wp:term>
      <wp:term_id>4</wp:term_id>
      <wp:term_taxonomy><![CDATA[category]]></wp:term_taxonomy>
      <wp:term_slug><![CDATA[blog]]></wp:term_slug>
      <wp:term_parent><![CDATA[]]></wp:term_parent>
      <wp:term_name><![CDATA[blog]]></wp:term_name>
    </wp:term>
      <wp:term>
      <wp:term_id>13</wp:term_id>
      <wp:term_taxonomy><![CDATA[post_tag]]></wp:term_taxonomy>
      <wp:term_slug><![CDATA[post]]></wp:term_slug>
      <wp:term_parent><![CDATA[]]></wp:term_parent>
      <wp:term_name><![CDATA[post]]></wp:term_name>
    </wp:term>
      <wp:term>
      <wp:term_id>2</wp:term_id>
      <wp:term_taxonomy><![CDATA[wp_theme]]></wp:term_taxonomy>
      <wp:term_slug><![CDATA[twentytwentythree]]></wp:term_slug>
      <wp:term_parent><![CDATA[]]></wp:term_parent>
      <wp:term_name><![CDATA[twentytwentythree]]></wp:term_name>
    </wp:term>
      <wp:term>
      <wp:term_id>1</wp:term_id>
      <wp:term_taxonomy><![CDATA[category]]></wp:term_taxonomy>
      <wp:term_slug><![CDATA[uncategorized]]></wp:term_slug>
      <wp:term_parent><![CDATA[]]></wp:term_parent>
      <wp:term_name><![CDATA[Uncategorized]]></wp:term_name>
    </wp:term>

    <generator>https://wordpress.org/?v=6.3.1</generator>

      <item>
      <title><![CDATA[Hello world!]]></title>
      <link>http://1.234.5.678/2023/08/27/hello-world/</link>
      <pubDate>Sun, 27 Aug 2023 23:54:12 +0000</pubDate>
      <dc:creator><![CDATA[user]]></dc:creator>
      <guid isPermaLink="false">http://127.0.0.1/?p=1</guid>
      <description></description>
      <content:encoded><![CDATA[<!-- wp:paragraph -->
  <p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>
  <!-- /wp:paragraph -->]]></content:encoded>
      <excerpt:encoded><![CDATA[]]></excerpt:encoded>
      <wp:post_id>1</wp:post_id>
      <wp:post_date><![CDATA[2023-08-27 23:54:12]]></wp:post_date>
      <wp:post_date_gmt><![CDATA[2023-08-27 23:54:12]]></wp:post_date_gmt>
      <wp:post_modified><![CDATA[2023-09-07 13:01:07]]></wp:post_modified>
      <wp:post_modified_gmt><![CDATA[2023-09-07 13:01:07]]></wp:post_modified_gmt>
      <wp:comment_status><![CDATA[open]]></wp:comment_status>
      <wp:ping_status><![CDATA[open]]></wp:ping_status>
      <wp:post_name><![CDATA[hello-world]]></wp:post_name>
      <wp:status><![CDATA[publish]]></wp:status>
      <wp:post_parent>0</wp:post_parent>
      <wp:menu_order>0</wp:menu_order>
      <wp:post_type><![CDATA[post]]></wp:post_type>
      <wp:post_password><![CDATA[]]></wp:post_password>
      <wp:is_sticky>0</wp:is_sticky>
                      <category domain="category" nicename="blog"><![CDATA[blog]]></category>
      <category domain="post_tag" nicename="post"><![CDATA[post]]></category>
      <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>
              <wp:postmeta>
      <wp:meta_key><![CDATA[footnotes]]></wp:meta_key>
      <wp:meta_value><![CDATA[]]></wp:meta_value>
      </wp:postmeta>
                <wp:postmeta>
      <wp:meta_key><![CDATA[_edit_last]]></wp:meta_key>
      <wp:meta_value><![CDATA[1]]></wp:meta_value>
      </wp:postmeta>
                <wp:comment>
        <wp:comment_id>1</wp:comment_id>
        <wp:comment_author><![CDATA[A WordPress Commenter]]></wp:comment_author>
        <wp:comment_author_email><![CDATA[wapuu@wordpress.example]]></wp:comment_author_email>
        <wp:comment_author_url>https://wordpress.org/</wp:comment_author_url>
        <wp:comment_author_IP><![CDATA[]]></wp:comment_author_IP>
        <wp:comment_date><![CDATA[2023-08-27 23:54:12]]></wp:comment_date>
        <wp:comment_date_gmt><![CDATA[2023-08-27 23:54:12]]></wp:comment_date_gmt>
        <wp:comment_content><![CDATA[Hi, this is a comment.
  To get started with moderating, editing, and deleting comments, please visit the Comments screen in the dashboard.
  Commenter avatars come from <a href="https://en.gravatar.com/">Gravatar</a>.]]></wp:comment_content>
        <wp:comment_approved><![CDATA[1]]></wp:comment_approved>
        <wp:comment_type><![CDATA[comment]]></wp:comment_type>
        <wp:comment_parent>0</wp:comment_parent>
        <wp:comment_user_id>0</wp:comment_user_id>
                </wp:comment>
            </item>
            <item>
      <title><![CDATA[Sample Page]]></title>
      <link>http://1.234.5.678/sample-page/</link>
      <pubDate>Sun, 27 Aug 2023 23:54:12 +0000</pubDate>
      <dc:creator><![CDATA[user]]></dc:creator>
      <guid isPermaLink="false">http://127.0.0.1/?page_id=2</guid>
      <description></description>
      <content:encoded><![CDATA[<!-- wp:paragraph -->
  <p>This is an example page. It's different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:</p>
  <!-- /wp:paragraph -->

  <!-- wp:quote -->
  <blockquote class="wp-block-quote"><p>Hi there! I'm a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin' caught in the rain.)</p></blockquote>
  <!-- /wp:quote -->

  <!-- wp:paragraph -->
  <p>...or something like this:</p>
  <!-- /wp:paragraph -->

  <!-- wp:quote -->
  <blockquote class="wp-block-quote"><p>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</p></blockquote>
  <!-- /wp:quote -->

  <!-- wp:paragraph -->
  <p>As a new WordPress user, you should go to <a href="http://127.0.0.1/wp-admin/">your dashboard</a> to delete this page and create new pages for your content. Have fun!</p>
  <!-- /wp:paragraph -->]]></content:encoded>
      <excerpt:encoded><![CDATA[]]></excerpt:encoded>
      <wp:post_id>2</wp:post_id>
      <wp:post_date><![CDATA[2023-08-27 23:54:12]]></wp:post_date>
      <wp:post_date_gmt><![CDATA[2023-08-27 23:54:12]]></wp:post_date_gmt>
      <wp:post_modified><![CDATA[2023-08-27 23:54:12]]></wp:post_modified>
      <wp:post_modified_gmt><![CDATA[2023-08-27 23:54:12]]></wp:post_modified_gmt>
      <wp:comment_status><![CDATA[closed]]></wp:comment_status>
      <wp:ping_status><![CDATA[open]]></wp:ping_status>
      <wp:post_name><![CDATA[sample-page]]></wp:post_name>
      <wp:status><![CDATA[publish]]></wp:status>
      <wp:post_parent>0</wp:post_parent>
      <wp:menu_order>0</wp:menu_order>
      <wp:post_type><![CDATA[page]]></wp:post_type>
      <wp:post_password><![CDATA[]]></wp:post_password>
      <wp:is_sticky>0</wp:is_sticky>
                              <wp:postmeta>
      <wp:meta_key><![CDATA[_wp_page_template]]></wp:meta_key>
      <wp:meta_value><![CDATA[default]]></wp:meta_value>
      </wp:postmeta>
                </item>
            <item>
      <title><![CDATA[Privacy Policy]]></title>
      <link>http://1.234.5.678/?page_id=3</link>
      <pubDate>Sun, 27 Aug 2023 23:54:12 +0000</pubDate>
      <dc:creator><![CDATA[user]]></dc:creator>
      <guid isPermaLink="false">http://127.0.0.1/?page_id=3</guid>
      <description></description>
      <content:encoded><![CDATA[<!-- wp:heading --><h2>Who we are</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong class="privacy-policy-tutorial">Suggested text: </strong>Our website address is: http://127.0.0.1.</p><!-- /wp:paragraph --><!-- wp:heading --><h2>Comments</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong class="privacy-policy-tutorial">Suggested text: </strong>When visitors leave comments on the site we collect the data shown in the comments form, and also the visitor&#8217;s IP address and browser user agent string to help spam detection.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>An anonymized string created from your email address (also called a hash) may be provided to the Gravatar service to see if you are using it. The Gravatar service privacy policy is available here: https://automattic.com/privacy/. After approval of your comment, your profile picture is visible to the public in the context of your comment.</p><!-- /wp:paragraph --><!-- wp:heading --><h2>Media</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you upload images to the website, you should avoid uploading images with embedded location data (EXIF GPS) included. Visitors to the website can download and extract any location data from images on the website.</p><!-- /wp:paragraph --><!-- wp:heading --><h2>Cookies</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you leave a comment on our site you may opt-in to saving your name, email address and website in cookies. These are for your convenience so that you do not have to fill in your details again when you leave another comment. These cookies will last for one year.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>If you visit our login page, we will set a temporary cookie to determine if your browser accepts cookies. This cookie contains no personal data and is discarded when you close your browser.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>When you log in, we will also set up several cookies to save your login information and your screen display choices. Login cookies last for two days, and screen options cookies last for a year. If you select &quot;Remember Me&quot;, your login will persist for two weeks. If you log out of your account, the login cookies will be removed.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>If you edit or publish an article, an additional cookie will be saved in your browser. This cookie includes no personal data and simply indicates the post ID of the article you just edited. It expires after 1 day.</p><!-- /wp:paragraph --><!-- wp:heading --><h2>Embedded content from other websites</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong class="privacy-policy-tutorial">Suggested text: </strong>Articles on this site may include embedded content (e.g. videos, images, articles, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other website.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>These websites may collect data about you, use cookies, embed additional third-party tracking, and monitor your interaction with that embedded content, including tracking your interaction with the embedded content if you have an account and are logged in to that website.</p><!-- /wp:paragraph --><!-- wp:heading --><h2>Who we share your data with</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you request a password reset, your IP address will be included in the reset email.</p><!-- /wp:paragraph --><!-- wp:heading --><h2>How long we retain your data</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you leave a comment, the comment and its metadata are retained indefinitely. This is so we can recognize and approve any follow-up comments automatically instead of holding them in a moderation queue.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>For users that register on our website (if any), we also store the personal information they provide in their user profile. All users can see, edit, or delete their personal information at any time (except they cannot change their username). Website administrators can also see and edit that information.</p><!-- /wp:paragraph --><!-- wp:heading --><h2>What rights you have over your data</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you have an account on this site, or have left comments, you can request to receive an exported file of the personal data we hold about you, including any data you have provided to us. You can also request that we erase any personal data we hold about you. This does not include any data we are obliged to keep for administrative, legal, or security purposes.</p><!-- /wp:paragraph --><!-- wp:heading --><h2>Where your data is sent</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong class="privacy-policy-tutorial">Suggested text: </strong>Visitor comments may be checked through an automated spam detection service.</p><!-- /wp:paragraph -->]]></content:encoded>
      <excerpt:encoded><![CDATA[]]></excerpt:encoded>
      <wp:post_id>3</wp:post_id>
      <wp:post_date><![CDATA[2023-08-27 23:54:12]]></wp:post_date>
      <wp:post_date_gmt><![CDATA[2023-08-27 23:54:12]]></wp:post_date_gmt>
      <wp:post_modified><![CDATA[2023-09-07 13:04:45]]></wp:post_modified>
      <wp:post_modified_gmt><![CDATA[2023-09-07 13:04:45]]></wp:post_modified_gmt>
      <wp:comment_status><![CDATA[closed]]></wp:comment_status>
      <wp:ping_status><![CDATA[open]]></wp:ping_status>
      <wp:post_name><![CDATA[privacy-policy]]></wp:post_name>
      <wp:status><![CDATA[draft]]></wp:status>
      <wp:post_parent>0</wp:post_parent>
      <wp:menu_order>0</wp:menu_order>
      <wp:post_type><![CDATA[page]]></wp:post_type>
      <wp:post_password><![CDATA[]]></wp:post_password>
      <wp:is_sticky>0</wp:is_sticky>
                              <wp:postmeta>
      <wp:meta_key><![CDATA[_wp_page_template]]></wp:meta_key>
      <wp:meta_value><![CDATA[default]]></wp:meta_value>
      </wp:postmeta>
                </item>
            <item>
      <title><![CDATA[Custom Styles]]></title>
      <link>http://1.234.5.678/2023/08/27/wp-global-styles-twentytwentythree/</link>
      <pubDate>Sun, 27 Aug 2023 23:58:17 +0000</pubDate>
      <dc:creator><![CDATA[user]]></dc:creator>
      <guid isPermaLink="false">http://1.234.5.678/2023/08/27/wp-global-styles-twentytwentythree/</guid>
      <description></description>
      <content:encoded><![CDATA[{"version": 2, "isGlobalStylesUserThemeJSON": true }]]></content:encoded>
      <excerpt:encoded><![CDATA[]]></excerpt:encoded>
      <wp:post_id>5</wp:post_id>
      <wp:post_date><![CDATA[2023-08-27 23:58:17]]></wp:post_date>
      <wp:post_date_gmt><![CDATA[2023-08-27 23:58:17]]></wp:post_date_gmt>
      <wp:post_modified><![CDATA[2023-08-27 23:58:17]]></wp:post_modified>
      <wp:post_modified_gmt><![CDATA[2023-08-27 23:58:17]]></wp:post_modified_gmt>
      <wp:comment_status><![CDATA[closed]]></wp:comment_status>
      <wp:ping_status><![CDATA[closed]]></wp:ping_status>
      <wp:post_name><![CDATA[wp-global-styles-twentytwentythree]]></wp:post_name>
      <wp:status><![CDATA[publish]]></wp:status>
      <wp:post_parent>0</wp:post_parent>
      <wp:menu_order>0</wp:menu_order>
      <wp:post_type><![CDATA[wp_global_styles]]></wp:post_type>
      <wp:post_password><![CDATA[]]></wp:post_password>
      <wp:is_sticky>0</wp:is_sticky>
                      <category domain="wp_theme" nicename="twentytwentythree"><![CDATA[twentytwentythree]]></category>
              </item>
            <item>
      <title><![CDATA[Navigation]]></title>
      <link>http://1.234.5.678/2023/08/28/navigation/</link>
      <pubDate>Mon, 28 Aug 2023 00:03:21 +0000</pubDate>
      <dc:creator><![CDATA[]]></dc:creator>
      <guid isPermaLink="false">https://1.234.5.678/2023/08/28/navigation/</guid>
      <description></description>
      <content:encoded><![CDATA[<!-- wp:page-list /-->]]></content:encoded>
      <excerpt:encoded><![CDATA[]]></excerpt:encoded>
      <wp:post_id>6</wp:post_id>
      <wp:post_date><![CDATA[2023-08-28 00:03:21]]></wp:post_date>
      <wp:post_date_gmt><![CDATA[2023-08-28 00:03:21]]></wp:post_date_gmt>
      <wp:post_modified><![CDATA[2023-08-28 00:03:21]]></wp:post_modified>
      <wp:post_modified_gmt><![CDATA[2023-08-28 00:03:21]]></wp:post_modified_gmt>
      <wp:comment_status><![CDATA[closed]]></wp:comment_status>
      <wp:ping_status><![CDATA[closed]]></wp:ping_status>
      <wp:post_name><![CDATA[navigation]]></wp:post_name>
      <wp:status><![CDATA[publish]]></wp:status>
      <wp:post_parent>0</wp:post_parent>
      <wp:menu_order>0</wp:menu_order>
      <wp:post_type><![CDATA[wp_navigation]]></wp:post_type>
      <wp:post_password><![CDATA[]]></wp:post_password>
      <wp:is_sticky>0</wp:is_sticky>
                              </item>
            <item>
      <title><![CDATA[logo]]></title>
      <link>http://1.234.5.678/logo/</link>
      <pubDate>Mon, 28 Aug 2023 09:41:31 +0000</pubDate>
      <dc:creator><![CDATA[user]]></dc:creator>
      <guid isPermaLink="false">http://1.234.5.678/wp-content/uploads/2023/08/logo.png</guid>
      <description></description>
      <content:encoded><![CDATA[]]></content:encoded>
      <excerpt:encoded><![CDATA[]]></excerpt:encoded>
      <wp:post_id>13</wp:post_id>
      <wp:post_date><![CDATA[2023-08-28 09:41:31]]></wp:post_date>
      <wp:post_date_gmt><![CDATA[2023-08-28 09:41:31]]></wp:post_date_gmt>
      <wp:post_modified><![CDATA[2023-08-28 09:41:31]]></wp:post_modified>
      <wp:post_modified_gmt><![CDATA[2023-08-28 09:41:31]]></wp:post_modified_gmt>
      <wp:comment_status><![CDATA[open]]></wp:comment_status>
      <wp:ping_status><![CDATA[closed]]></wp:ping_status>
      <wp:post_name><![CDATA[logo]]></wp:post_name>
      <wp:status><![CDATA[inherit]]></wp:status>
      <wp:post_parent>0</wp:post_parent>
      <wp:menu_order>0</wp:menu_order>
      <wp:post_type><![CDATA[attachment]]></wp:post_type>
      <wp:post_password><![CDATA[]]></wp:post_password>
      <wp:is_sticky>0</wp:is_sticky>
              <wp:attachment_url><![CDATA[http://1.234.5.678/wp-content/uploads/2023/08/logo.png]]></wp:attachment_url>
                        <wp:postmeta>
      <wp:meta_key><![CDATA[_wp_attached_file]]></wp:meta_key>
      <wp:meta_value><![CDATA[2023/08/logo.png]]></wp:meta_value>
      </wp:postmeta>
                <wp:postmeta>
      <wp:meta_key><![CDATA[_wp_attachment_metadata]]></wp:meta_key>
      <wp:meta_value><![CDATA[a:6:{s:5:"width";i:400;s:6:"height";i:400;s:4:"file";s:16:"2023/08/logo.png";s:8:"filesize";i:9128;s:5:"sizes";a:2:{s:6:"medium";a:5:{s:4:"file";s:16:"logo-300x300.png";s:5:"width";i:300;s:6:"height";i:300;s:9:"mime-type";s:9:"image/png";s:8:"filesize";i:3427;}s:9:"thumbnail";a:5:{s:4:"file";s:16:"logo-150x150.png";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:9:"image/png";s:8:"filesize";i:1518;}}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
      </wp:postmeta>
                </item>
            <item>
      <title><![CDATA[file_example_mp3_700kb]]></title>
      <link>http://1.234.5.678/file_example_mp3_700kb/</link>
      <pubDate>Thu, 31 Aug 2023 21:55:03 +0000</pubDate>
      <dc:creator><![CDATA[user]]></dc:creator>
      <guid isPermaLink="false">http://1.234.5.678/wp-content/uploads/2023/08/file_example_mp3_700kb.mp3</guid>
      <description></description>
      <content:encoded><![CDATA[]]></content:encoded>
      <excerpt:encoded><![CDATA[]]></excerpt:encoded>
      <wp:post_id>19</wp:post_id>
      <wp:post_date><![CDATA[2023-08-31 21:55:03]]></wp:post_date>
      <wp:post_date_gmt><![CDATA[2023-08-31 21:55:03]]></wp:post_date_gmt>
      <wp:post_modified><![CDATA[2023-08-31 21:55:03]]></wp:post_modified>
      <wp:post_modified_gmt><![CDATA[2023-08-31 21:55:03]]></wp:post_modified_gmt>
      <wp:comment_status><![CDATA[open]]></wp:comment_status>
      <wp:ping_status><![CDATA[closed]]></wp:ping_status>
      <wp:post_name><![CDATA[file_example_mp3_700kb]]></wp:post_name>
      <wp:status><![CDATA[inherit]]></wp:status>
      <wp:post_parent>0</wp:post_parent>
      <wp:menu_order>0</wp:menu_order>
      <wp:post_type><![CDATA[attachment]]></wp:post_type>
      <wp:post_password><![CDATA[]]></wp:post_password>
      <wp:is_sticky>0</wp:is_sticky>
              <wp:attachment_url><![CDATA[http://1.234.5.678/wp-content/uploads/2023/08/file_example_mp3_700kb.mp3]]></wp:attachment_url>
                        <wp:postmeta>
      <wp:meta_key><![CDATA[_wp_attached_file]]></wp:meta_key>
      <wp:meta_value><![CDATA[2023/08/file_example_mp3_700kb.mp3]]></wp:meta_value>
      </wp:postmeta>
                <wp:postmeta>
      <wp:meta_key><![CDATA[_wp_attachment_metadata]]></wp:meta_key>
      <wp:meta_value><![CDATA[a:20:{s:10:"dataformat";s:3:"mp3";s:8:"channels";i:2;s:11:"sample_rate";i:32000;s:7:"bitrate";i:224000;s:11:"channelmode";s:6:"stereo";s:12:"bitrate_mode";s:3:"cbr";s:5:"codec";s:4:"LAME";s:7:"encoder";s:9:"LAME3.99r";s:8:"lossless";b:0;s:15:"encoder_options";s:20:"--alt-preset cbr 224";s:17:"compression_ratio";d:0.21875;s:10:"fileformat";s:3:"mp3";s:8:"filesize";i:764176;s:9:"mime_type";s:10:"audio/mpeg";s:6:"length";i:27;s:16:"length_formatted";s:4:"0:27";s:5:"genre";s:9:"Cinematic";s:5:"album";s:21:"YouTube Audio Library";s:5:"title";s:15:"Impact Moderato";s:6:"artist";s:13:"Kevin MacLeod";}]]></wp:meta_value>
      </wp:postmeta>
                </item>
          </channel>
  </rss>
    `;
