export { FileHandler } from '@tiptap-pro/extension-file-handler';
export { BulletList } from '@tiptap/extension-bullet-list';
export { CharacterCount } from '@tiptap/extension-character-count';
export { CodeBlock } from '@tiptap/extension-code-block';
export { Collaboration } from '@tiptap/extension-collaboration';
export { Dropcursor } from '@tiptap/extension-dropcursor';
export { OrderedList } from '@tiptap/extension-ordered-list';
export { Paragraph } from '@tiptap/extension-paragraph';
export { Placeholder } from '@tiptap/extension-placeholder';
export { TaskItem } from '@tiptap/extension-task-item';
export { Underline } from '@tiptap/extension-underline';
export { StarterKit } from '@tiptap/starter-kit';
export { CodeBlockLowlight } from '@tiptap/extension-code-block-lowlight';

export { HorizontalRule } from './HorizontalRule/index.js';
export { ImageBlock } from './ImageBlock/index.js';
export { ImageUpload } from './ImageUpload/ImageUpload.js';
export { Link } from './Link/index.js';
export { SlashCommand } from './SlashCommand/index.js';
