name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: yarn install
        run: yarn install

      - name: Type Check
        run: yarn typecheck

      - name: Prettier
        run: yarn format

      - name: Run ESLint
        run: yarn lint

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: yarn install
        run: yarn install

      - name: Component Tests
        run: yarn test:components
