name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      TIPTAP_PRO_TOKEN: ${{ secrets.TIPTAP_PRO_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        node-version: ['20.14.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Create .npmrc file
      #   run: |
      #     echo "@tiptap-pro:registry=https://registry.tiptap.dev/" >> .npmrc
      #     echo "//registry.tiptap.dev/:_authToken=${{ secrets.TIPTAP_PRO_TOKEN }}" >> .npmrc

      - name: install
        run: yarn install

      - name: Type Check
        run: yarn typecheck

      - name: Prettier
        run: yarn format

      - name: Run ESLint
        run: yarn lint
