name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      TIPTAP_PRO_TOKEN: ${{ secrets.TIPTAP_PRO_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        node-version: ['20.14.x']
        database:
          - postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn install

      - name: Start Services
        run: docker compose -f test/docker-compose.yml up ${{ matrix.database }} -d --quiet-pull --wait

      - name: Run Tests
        run: yarn test:int --runInBand
