name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - src/api/**
      - test/api/**
      - package.json
      - .github/workflows/integration-full.yml

concurrency:
  group: integration-main
  cancel-in-progress: true

jobs:
  integration:
    name: ${{ matrix.database }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database:
          - sqlite3
          - mysql
          - maria
          - postgres
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Yarn install
        run: yarn install

      - name: Start Services
        if: matrix.database != 'sqlite3'
        run: docker compose -f test/docker-compose.yml up ${{ matrix.database }} -d --quiet-pull --wait

      - name: Run Tests
        run: TEST_DB=${{ matrix.database }} yarn test:int
